import os
print("Installation des librairies")
print("===========================")
print("Installation de Flask")
os.system("pip3 install flask")
print("===========================")
print("Installation de flask_socketio")
os.system("pip3 install flask_socketio")
print("===========================")
print("Installation de obs-ws-rc")
os.system("pip3 install obs-ws-rc")
print("===========================")
print("Installation de obs-websocket-py")
os.system("pip3 install obs-websocket-py")
print("===========================")
print("===========================")
print("===========================")
print("===========================")
print("FIN")